## main.yml
name: wakinchan-work
on:
    push:
      branches:
        - master

jobs:
    build:
        name: build hugo projects
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v1
              with:
                submodules: true
                fetch-depth: 0
            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                hugo-version: 'latest'
            - name: Build hugo pages
              run: |
                hugo --minify
            - name: Archive Production Artifact
              uses: actions/upload-artifact@master
              with:
                name: public
                path: public
    deploy:
        name: Deploy
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
            - name: Download Artifact
              uses: actions/download-artifact@master
              with:
                name: public
            - name: Deploy to Firebase
              uses: w9jds/firebase-action@master
              with:
                args: deploy --only hosting
              env:
                FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
                PROJECT_ID: wakincan-work